### ISSUE TITLE
脚手架init时的driver不匹配， 填的是redis， 生成的是discover/consul

### ISSUE THREAD

**Issue by 18321356127** [khgame/turtle#1]
脚手架 init 时的 driver 不匹配, 填的是 redis, 生成的是discover/consul
只有 index.ts 里的 driver 生成的是 [ "consul" ]
而配置生成的还是 redis 的配置，启动时会报 config of driver discovrt/consul are not exist

**Comment by bagaking** [comment]
默认的初始化不会有这个问题, 已知可能的情况应该是被 index template 覆盖了
是否使用了 tur-web 模板?

**Comment by 18321356127** [comment]
填的是 web，用的是 https://github.com/khgame/tur-web

**Comment by bagaking** [comment]
嗯 这是因为 tur-web 里没有提供默认配置, 使用 tur-web 的时候 drivers 需要填对应的 mongo 和 discover/consul
我刚才在 turtle 和 tur-web 各提交了一版修改,  给脚手架提供了 replacer 机制并对应修改了 tur-web 里的内容, 现在已经可以在使用 tur-web 时自定义 driver 了

**Comment by bagaking** [comment]
https://www.npmjs.com/package/@khgame/turtle/v/0.0.80
