### ISSUE TITLE
getLoosingCache在某些情况下刷新后第一次返回与之后返回的结果不一致

### ISSUE THREAD

**Issue by irushx** [khgame/turtle#2]
从mongo取出schemaType为map的值后，刷新后第一次与之后的返回结果不一致
sample：
第一次，ftsIssued:
10200100: "2800"
之后，ftsIssued:
$__parent: {tx_ids: Array(0), _id: "10000003", fts: {…}, cas: 29, create_at: "2019-08-19T10:14:45.658Z", …}
$__path: "fts"
$__schemaType: {path: "fts.$*", validators: Array(0), getters: Array(0), setters: Array(0), options: {…}, …}
__proto__: Object

**Comment by bagaking** [comment]
这描述对应两个问题:

1. 数据解析异常

    这是因为 set cache 时进行了数据拷贝, 和原始结构有一些差异.
    目前使用的 cache 库是 node cache, 具体缓存时的数据处理可以看下这两个库 :

    - https://github.com/mpneuried/nodecache
    - https://github.com/pvorb/clone
    
    另外这个也和你生成数据的方式(或库)有关, 如果比较难处理, 可以先序列化或者在 option 中开启 cache 的 forceString 选项.

2. 前后数据不一致

    第一次查询的结果是写缓存并直接返回的, 这个确实有点问题, 我来处理一下

**Comment by bagaking** [comment]
https://www.npmjs.com/package/@khgame/turtle/v/0.0.83
